name: Notify Local API

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify Local API
      env:
        API_ENDPOINT: http://localhost:3000  # Replace with the URL of your local API
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"branch": "main", "message": "Files have been changed."}' \
          $API_ENDPOINT
