name: Notification
on: 
  workflow_run:
    workflows: ["Validate", "Deploy"]
    types:
      - completed
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[Notification] Job \"${{ github.event.workflow_run.name }}\" in ${{ github.repository }} has ${{ github.event.workflow_run.conclusion }}"
          body: Job ${{ github.event.workflow_run.name }} of ${{ github.repository }} has ${{ github.event.workflow_run.conclusion }}
          to: haupro186@gmail.com,minhlam2102002@gmail.com
          from: TheThree
