name: Validate
on: [pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  doctor-rst:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: DOCtor-RST
          uses: docker://oskarstark/doctor-rst
          with:
            args: --short --error-format=github
          env:
            DOCS_DIR: '../../docs/'
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install actions-toolkit
      - name: Run consistency check
        run: |
          python validate.py -i docs/src/
